# Generated by Django 4.2 on 2024-04-11 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description_short', models.TextField()),
                ('description_long', models.TextField()),
                ('lng', models.DecimalField(decimal_places=15, max_digits=18)),
                ('lat', models.DecimalField(decimal_places=15, max_digits=18)),
            ],
        ),
    ]
