# Generated by Django 4.2 on 2024-04-23 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('places', '0006_alter_image_options_alter_place_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(unique=True, upload_to='', verbose_name='Изображение'),
        ),
    ]
